#!/bin/bash
Off='\033[0m'
# Regular Colors
Black='\033[0;30m'        # Black
R='\033[0;31m'          # Red
G='\033[0;32m'        # Green
Y='\033[0;33m'       # Yellow
B='\033[0;34m'         # Blue
P='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

echo -e "${B}Choose an option for the OpenAI engine${Off}\n"
echo -e "${Cyan}1. Davinci 3 (Recommended)"
echo "2. Davinci 2"
echo "3. Curie 1"
echo "4. Babbage 1"
echo -e "5. ADA 1 ${Y} \n"

read -p "Enter a number: " choice

case $choice in
    1) engine="text-davinci-003";;
    2) engine="text-davinci-002";;
    3) engine="text-curie-001";;
    4) engine="text-babbage-001";;
    5) engine="text-ada-001";;
    *) echo "Invalid choice"; exit 1;;
esac

# Update gpt.py with the chosen engine
sed -i "s/engine=\".*\"/engine=\"$engine\"/" ~/CLI-GPT/gpt.py

echo -e "${G}Engine successfully updated to $engine in gpt.py${Off}"
