#!/bin/bash

Color_Off='\033[0m'
# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Install required packages
# sudo apt-get update
# sudo apt-get install python3-pip -y
pip3 install openai

# Give script perms
chmod +x ./gpt
chmod +x ./update

echo "Welcome to the first time setup for CLI-GPT"

read -p "Please enter your OpenAI API key: " key

# Replace the API key in gpt.py
sed -i "s/openai.api_key = \"\"/openai.api_key = \"$key\"/" gpt.py

echo "API key successfully updated in gpt.py"

echo "alias gpt='python3 ~/CLI-GPT/gpt.py'" >> ~/.bashrc
echo "alias gpt-update='python3 ~/CLI-GPT/update'" >> ~/.bashrc

echo "Setup complete!"

source ~/.bashrc
