#!/bin/bash

# Install required packages
# sudo apt-get update
# sudo apt-get install python3-pip -y
pip3 install openai

# Give script perms
chmod +x ./gpt
chmod +x ./update

echo "Welcome to the first time setup for CLI-GPT"

echo "Please enter your OpenAI API key: "
read key

# Replace the API key in gpt.py
sed -i "s/openai.api_key = \"\"/openai.api_key = \"$key\"/" gpt.py

echo "API key successfully updated in gpt.py"

echo "alias gpt='python3 ~/CLI-GPT/gpt.py'" >> ~/.bashrc
echo "alias gpt-update='python3 ~/CLI-GPT/update'" >> ~/.bashrc

echo "Setup complete!"
