#!/bin/bash

source ~/CLI-GPT/extras/colors

config_file="$HOME/.config/cli-gpt.conf"

update_options () {
source $config_file
if [ "$ALWAYS_OVERWRITE_ALIASES" == "true" ]; then
    aliases_set="[✓]"
else
    aliases_set="[ ]"
fi

if [ "$ALWAYS_KEEP_API_KEY" == "true" ]; then
    keep_key="[✓]"
else
    keep_key="[ ]"
fi

if [ "$UPDATE_NOTIFICATION" == "false" ]; then
    noti="[✓]"
else
    noti="[ ]"
fi
}
update_options

print_options () {
echo -e "\n${G}CLI-GPT settings:${Cyan}\n"
echo -e "1. Always overwrite '~/.bash_aliases'    ${B}$aliases_set${Cyan}"
echo -e "2. Always keep API key                   ${B}$keep_key${Cyan}"
echo -e "3. Turn off update notification          ${B}$noti \n${Y}"
read -p "Enter an option (exit to leave): " select
}

print_options

while true; do
case $select in
    1)
        read -p "Do want to always overwrite '~/.bash_aliases'? (Y/n): " overwrite_aliases
        if [[ $overwrite_aliases =~ ^[Nn]$ ]]; then
            sed -i "s/^ALWAYS_OVERWRITE_ALIASES=.*/ALWAYS_OVERWRITE_ALIASES=false/" "$config_file"
            clear
            update_options
            print_options
        else
            new_overwrite_aliases=true
            sed -i "s/^ALWAYS_OVERWRITE_ALIASES=.*/ALWAYS_OVERWRITE_ALIASES=$new_overwrite_aliases/" "$config_file"
            clear
            update_options
            print_options
        fi
        ;;
    2)
        read -p "Do want to always keep your API key? (Y/n): " keep_api_key
        if [[ $keep_api_key =~ ^[Nn]$ ]]; then
            sed -i "s/^ALWAYS_KEEP_API_KEY=.*/ALWAYS_KEEP_API_KEY=false/" "$config_file"
            clear
            update_options
            print_options
        else
            new_keep_api_key=true
            sed -i "s/^ALWAYS_KEEP_API_KEY=.*/ALWAYS_KEEP_API_KEY=$new_keep_api_key/" "$config_file"
            clear
            update_options
            print_options
        fi
        ;;
    3)
        read -p "Do want to turn OFF the update notification when running 'gpt'? (Y/n): " update_notification
        if [[ $update_notification =~ ^[Nn]$ ]]; then
            sed -i "s/^UPDATE_NOTIFICATION=.*/UPDATE_NOTIFICATION=true/" "$config_file"
            clear
            update_options
            print_options
        else
            new_update_notification=false
            sed -i "s/^UPDATE_NOTIFICATION=.*/UPDATE_NOTIFICATION=$new_update_notification/" "$config_file"
            clear
            update_options
            print_options
        fi
        ;;
     exit|x|q|quit)
        exit
        ;;
    *)
        clear
        echo "Invalid option."
        print_options
        ;;
esac
done
