#!/bin/bash

# Import Colors
source ~/CLI-GPT/extras/colors

# Create config file
echo "ALWAYS_OVERWRITE_ALIASES=false" > ~/.config/cli-gpt.conf
echo "ALWAYS_KEEP_API_KEY=false" >> ~/.config/cli-gpt.conf
echo "UPDATE_NOTIFICATION=true" >> ~/.config/cli-gpt.conf

echo -e "\n${Cyan}Welcome to the first time setup for CLI-GPT!${Off}\n"

# sudo apt install python3-pip -y
# Check for required packages
if python3 -c "import openai" &> /dev/null; then
    echo -e "${G}pip3 module 'openai' was found!${Off}"
else
    pip3 install openai
fi
if python3 -c "import colorama" &> /dev/null; then
    echo -e "${G}pip3 module 'colorama' was found!${Off}"
else
    pip3 install colorama
fi
if python3 -c "import requests" &> /dev/null; then
    echo -e "${G}pip3 module 'requests' was found!${Off}"
else
    pip3 install requests
fi

# Give script perms
chmod +x $HOME/CLI-GPT/update
chmod +x $HOME/CLI-GPT/settings
chmod +x $HOME/CLI-GPT/change-engine
chmod +x $HOME/CLI-GPT/tone
chmod +x $HOME/CLI-GPT/extras/defaults

# Ask for API Key
echo -e "${Y}"
read -p "Please enter your OpenAI API key ('CTRL + SHIFT + V' to paste): " key
echo -e "${Off}"

# Replace the API key in gpt.py
sed -i "s/openai.api_key = \"\"/openai.api_key = \"$key\"/" ~/CLI-GPT/gpt.py

echo -e "${G}API key successfully updated in ${BGreen}'gpt.py'${Y}"

# Function for adding aliases to .bash_aliases
add_aliases () {
  echo -e "alias gpt='python3 ~/CLI-GPT/gpt.py'" > ~/.bash_aliases
  echo -e "alias gpt-update='bash ~/CLI-GPT/update && source ~/.bash_aliases'" >> ~/.bash_aliases
  echo -e "alias gpt-engine='bash ~/CLI-GPT/change-engine'" >> ~/.bash_aliases
  echo -e "alias gpt-tone='bash ~/CLI-GPT/tone'" >> ~/.bash_aliases
  echo -e "alias gpt-default='bash ~/CLI-GPT/extras/defaults'" >> ~/.bash_aliases
  echo -e "alias gpt-settings='bash ~/CLI-GPT/settings'" >> ~/.bash_aliases
  echo -e "${G}Aliases added successfully in ${BGreen}'~/.bash_aliases'${Off}"
}

if [ -f ~/.bash_aliases ]; then
    echo -e "Please understand ${BYellow}'~/.bash_aliases'${Off}${Y} will be overwritten! This is recommended for most users. "
    read -p "Do wish to continue? (Y/n): " overwrite_aliases
    if [ "$overwrite_aliases" == "n" ] || [ "$overwrite_aliases" == "N" ]; then
        echo -e "${R}NOTICE: setup will continue, but will have to execute commands manually (python3 ~/CLI-GPT/gpt.py)!${Off}"
    else
        add_aliases
    fi
else
    sed -i "s/ALWAYS_OVERWRITE_ALIASES=.*/ALWAYS_OVERWRITE_ALIASES=true/" ~/.config/cli-gpt.conf
    add_aliases
fi

echo -e "${G}Setup complete!${Off}\n"

# List commands
echo -e "${B}Commands:"        
echo -e "${BBlue}gpt${B}           - begin ChatGPT conversation"
echo -e "${BBlue}gpt-update${B}    - update CLI-GPT code"
echo -e "${BBlue}gpt-tone${B}      - change ChatGPT's tone and writing style"
echo -e "${BBlue}gpt-settings${B}  - change CLI-GPT settings"
echo -e "${BBlue}gpt-engine${B}    - change OpenAI engine"
echo -e "${BBlue}gpt-default${B}   - revert engine, tone, and writing style to defaults${Off}"

cd $HOME
exec bash
