#!/bin/bash

Off='\033[0m'
# Regular Colors
Black='\033[0;30m'        # Black
R='\033[0;31m'          # Red
G='\033[0;32m'        # Green
Y='\033[0;33m'       # Yellow
B='\033[0;34m'         # Blue
P='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
W='\033[0;37m'        # White

echo -e "${Cyan}Welcome to the first time setup for CLI-GPT!${Off}"

# Install required packages
# sudo apt-get update
# sudo apt-get install python3-pip -y
pip3 install openai

# Give script perms
chmod +x ~/CLI-GPT/gpt
chmod +x ~/CLI-GPT/update

echo -e "${Y}"
read -p "Please enter your OpenAI API key ('CTRL + SHIFT + V' to paste): " key
echo -e "${Off}"

# Replace the API key in gpt.py
sed -i "s/openai.api_key = \"\"/openai.api_key = \"$key\"/" ~/CLI-GPT/gpt.py

echo -e "${G}API key successfully updated in 'gpt.py'${Off}"

# checks if the aliases are already present
alias_check='$(alias -p | grep -om 1 "python3 ~/CLI-GPT/gpt.py")'
if [ "$alias_check" == "python3 ~/CLI-GPT/gpt.py" ]; then
    echo -e "${Y}Aliases are already set!${Off}"
else
    echo -e "${Cyan}Adding 'gpt' and 'gpt-update' aliases...${Off}"
    echo "alias gpt='python3 ~/CLI-GPT/gpt.py'" >> ~/.bashrc
    echo "alias gpt-update='bash ~/CLI-GPT/update'" >> ~/.bashrc
fi

echo -e "${G}Setup complete!${Off}"
echo -e "${B}### Commands:"        
echo -e "gpt           - begin ChatGPT conversation"
echo -e "gpt-update    - update CLI-GPT code${Off}"
cd ~
bash
