#!/bin/bash
Off='\033[0m'
# Regular Colors
Black='\033[0;30m'        # Black
R='\033[0;31m'          # Red
G='\033[0;32m'        # Green
Y='\033[0;33m'       # Yellow
B='\033[0;34m'         # Blue
P='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
W='\033[0;37m'        # White

cd /home/$USER/
rm -rf CLI-GPT/

echo -e "\n${Cyan}Welcome to the updater for CLI-GPT!${Off}\n"

git clone https://github.com/TETRA326/CLI-GPT.git

# Install required packages
# sudo apt-get update
# sudo apt-get install python3-pip -y
pip3 install openai
pip3 install colorama

# Give script perms
chmod +x /home/$USER/CLI-GPT/gpt
chmod +x /home/$USER/CLI-GPT/update
chmod +x /home/$USER/CLI-GPT/change-engine
chmod +x /home/$USER/CLI-GPT/tone

echo -e "${Y}"
read -p "Please enter your OpenAI API key ('CTRL + SHIFT + V' to paste): " key
echo -e "${Off}"

# Replace the API key in gpt.py
sed -i "s/openai.api_key = \"\"/openai.api_key = \"$key\"/" /home/$USER/CLI-GPT/gpt.py

echo -e "${G}API key successfully updated in 'gpt.py'${Y}"

echo -e "Please understand '~/.bash_aliases' will be overwritten! This is recommended for most users. "
read -p "Do wish to continue? (Y/n): " overwrite_aliases

if [ "$overwrite_aliases" == "n" ] || [ "$overwrite_aliases" == "N" ]; then
    echo -e "${R}NOTICE: setup will continue, but will have to execute commands manually (bash ~/CLI-GPT/gpt)!${Off}"
else
    echo -e "alias gpt='python3 ~/CLI-GPT/gpt.py'\nalias gpt-update='bash ~/CLI-GPT/update'\nalias gpt-engine='bash ~/CLI-GPT/change-engine'" > ~/.bash_aliases
    echo -e "${G}Aliases added successfully.${Off}"
fi

echo -e "${G}Update complete!${Off}\n"
echo -e "${B}Commands:"        
echo -e "gpt           - begin ChatGPT conversation"
echo -e "gpt-update    - update CLI-GPT code"
echo -e "gpt-engine    - change OpenAI engine${Off}"
